/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package triplets;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertNotNull;

class TripletsCodeTest {
    @Test void appHasAGreeting() {
        TripletsCode classUnderTest = new TripletsCode();
        assertNotNull(classUnderTest, "app should have a greeting");
    }
}
