/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hamming.code;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class HammingCodeTest {
    @Test void appHasAGreeting() {
        HammingCode classUnderTest = new HammingCode();
        assertNotNull(classUnderTest, "app shouldn't be null");
    }
}
